services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    build: .
    command: sh -c "sleep 5 && pytest -s -vv && alembic upgrade head && python main.py"
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "10000:10000"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge